spring.application.name=secure_desk

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/secure_desk_db
spring.datasource.username=postgres
spring.datasource.password=Manuel2309lm6


